# Generated by Django 3.0 on 2020-09-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('userAccount', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('userPassword', models.CharField(max_length=15)),
            ],
        ),
    ]
