# Generated by Django 3.0 on 2020-09-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerAccount',
            fields=[
                ('managerAccount', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('managerPassword', models.CharField(max_length=15)),
            ],
        ),
    ]
