# Generated by Django 3.0 on 2020-09-17 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_auto_20200917_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Login.Account')),
                ('name', models.CharField(max_length=20)),
                ('birthday', models.DateField(auto_now_add=True)),
                ('sexIsMale', models.BooleanField(default=True)),
                ('college', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
