# Generated by Django 3.0 on 2020-09-17 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='sexIsMale',
            new_name='isMale',
        ),
    ]
