# Generated by Django 3.1.1 on 2020-09-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_commodity_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodity',
            old_name='Description',
            new_name='description',
        ),
    ]
