# Generated by Django 3.1.1 on 2020-11-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_commodity_image'),
        ('Model', '0002_auto_20200923_1949'),
    ]

    operations = [
    ]
